name: CI

on: pull_request

jobs:
  check:
    name: Automated checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint files
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build
